version: 2
jobs:
    checkout:
        working_directory: ~/repo
        docker:
            - image: circleci/node:latest
        steps:
            - checkout:
                  path: ~/repo

    unit_test:
        working_directory: ~/repo/
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - node/install-packages:
                  override-ci-command: yarn install
            - run:
                  name: Unit Test
                  command: yarn test --ci --runInBand
    compile:
        working_directory: ~/repo/
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - node/install-packages:
                  override-ci-command: yarn install
            - run:
                  name: Compile
                  command: 'yarn compile'
    deploy:
        working_directory: ~/repo/
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - node/install-packages:
                  override-ci-command: yarn install
            - run:
                  name: Deploy
                  command: 'yarn deploy'
workflows:
    version: 2
    build_and_test:
        jobs:
            - checkout
            - unit_test:
                  requires:
                      - checkout
            - compile:
                  requires:
                      - unit_test
            - deploy:
                  requires:
                      - compile
                  filters:
                      branches:
                          only: master
