version: 2
jobs:
    checkout:
        working_directory: ~/repo
        docker:
            - image: cimg/node:16.17
        steps:
            - checkout:
                  path: ~/repo
    unit_test:
        working_directory: ~/repo/
        docker:
            - image: cimg/node:16.17
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: yarn install --immutable
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  name: Unit Test
                  command: yarn test --ci --runInBand
    compile:
        working_directory: ~/repo/
        docker:
            - image: cimg/node:16.17
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: yarn install --immutable
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  name: Compile
                  command: 'yarn compile'
    deploy:
        working_directory: ~/repo/
        docker:
            - image: cimg/node:16.17
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: yarn install --immutable
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  command: 'git config --global user.email "sccdmaomoa@hotmail.com'
            - run:
                  command: 'git config --global user.name "Guohao Yan'
            - run:
                  name: Deploy
                  command: 'yarn deploy'
workflows:
    version: 2
    build_and_test:
        jobs:
            - checkout
            - unit_test:
                  requires:
                      - checkout
            - compile:
                  requires:
                      - checkout
            - deploy:
                  requires:
                      - compile
                  filters:
                      branches:
                          only: master
