version: 2
jobs:
    checkout:
        working_directory: ~/repo
        docker:
            - image: circleci/node:latest
        steps:
            - checkout:
                  path: ~/repo
            - save_cache:
                  key: dependency-cache-{{ .Branch }}-{{ .Revision }}
                  paths:
                      - /node_modules/
    unit_test:
        working_directory: ~/repo/
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - dependency-cache-{{ .Branch }}-{{ .Revision }}
                      - dependency-cache-{{ .Branch }
                      - dependency-cache-
            - run:
                  name: Checkout from cache
                  command: git checkout -f
            - restore_cache:
                  keys:
                      - dependency-cache-{{ .Branch }}-{{ .Revision }}
                      - dependency-cache-{{ .Branch }
                      - dependency-cache-
            - run: 'yarn install'
            - run:
                  name: Unit Test
                  command: yarn test --ci --runInBand
    compile:
        working_directory: ~/repo/
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - dependency-cache-{{ .Branch }}-{{ .Revision }}
                      - dependency-cache-{{ .Branch }
                      - dependency-cache-
            - run:
                  name: Compile
                  command: 'yarn install && yarn compile'
    deploy:
        working_directory: ~/repo/
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - dependency-cache-{{ .Branch }}-{{ .Revision }}
                      - dependency-cache-{{ .Branch }
                      - dependency-cache-
            - add_ssh_keys:
                  fingerprints:
                      - 'bf:5a:5d:47:40:00:ee:05:4c:f6:59:9c:82:e3:ff:ff'
            - run:
                  name: Install
                  command: |
                      yarn install
                      git config user.email "sccdmaomao@hotmail.com"
                      git config user.name "ci-build"

            - run:
                  name: Deploy
                  command: 'yarn deploy'
workflows:
    version: 2
    build_and_test:
        jobs:
            - checkout
            - unit_test:
                  requires:
                      - checkout
            - compile:
                  requires:
                      - unit_test
            - deploy:
                  requires:
                      - compile
